#!/bin/sh

#LAUNCHERS
$HOME/.config/bspwm/autostart.sh

#BSPWM configuration
#bspc config border_radius       8
bspc config border_width         15
bspc config window_gap           8
#bspc config top_padding          30
#bspc config bottom_padding       10
bspc config left_padding         10
bspc config right_padding        10
bspc config single_monocle       false
#bspc config click_to_focus       true
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#bspc config focus_by_distance    true
bspc config focus_follows_pointer true
#bspc config history_aware_focus  true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

#BSPWM coloring
bspc config normal_border_color		"#32302f"
bspc config active_border_color		"#32302f"
# bspc config focused_border_color	    "#b8bb26"
bspc config focused_border_color	    "#ebdbb2"
# bspc config focused_border_color	"#e27878"
bspc config presel_feedback_color	"#1d2021"
# bspc config urgent_border_color 	"#dd2727"


#Single monitor
#bspc monitor -d 1 2 3 4 5 6

#Dual monitor
bspc monitor DisplayPort-0 -d 1 2 3 4 5 6
bspc monitor HDMI-A-0 -d 1 2 3 4 5 6
#find out names with arandr or xrandr
#bspc monitor DP-2 -d 1 2 3 4 5 6 7 8 9
#bspc monitor LVDS1 -d 1 2 3 4
#bspc monitor DP3 -d  5 6 7 8 9
#bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8 9 10
bspc monitor HDMI-1 -d 1 2 3 4 5 6 
#bspc monitor HDMI1 -d 1 2 3 4 5
#bspc monitor HDMI2 -d 6 7 8 9 10

#Fullscreen applications
# bspc rule -a mpv state=fullscreen

#Floating applications
bpsc rule -a mpv state=floating rectangle=1600x900+1000+100
bspc rule -a feh state=floating
bspc rule -a Alacritty state=floating rectangle=900x400+100+100
bspc rule -a ffplay state=floating rectangle=500x300+3315+75
bspc rule -a "Emacs-29.1" state=floating rectangle=2970x1660+55+125

#Tiled applications
bspc rule -a Gnome-disks state=tiled
bspc rule -a Xfce4-settings-manager state=tiled
bspc rule -a Zathura state=tiled
# bspc rule -a Emacs state=tiled
# bspc rule -a emacs-29-1 state=tiled
# bspc rule -a "Emacs-29.1" state=tiled

bspc rule -a scpad sticky=on state=floating rectangle=1500x1000+1150+450
bspc rule -a matplotlib state=floating
xsetroot -cursor_name left_ptr &

pkill double_border; ~/.config/bspwm/scripts/double_border &
