# first things  first
setxkbmap -option caps:escape
autoload -Uz compinit
autoload -Uz colors && colors

# faster repeating keystrokes
xset r rate 210 40

# tha prompt
PROMPT="%B%{$fg[blue]%}[%{$fg[white]%}%n%{$fg[red]%}@%{$fg[white]%}%m%{$fg[blue]%}] %(?:%{$fg_bold[green]%}➜ :%{$fg_bold[red]%}➜ )%{$fg[cyan]%}%c%{$reset_color%}  : "


# vim binds
bindkey -v
bindkey "^R" history-incremental-search-backward # but keep this as it is

# path shenanigans
export GOPATH=$HOME/go
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin:~/.cargo/bin

# pywal support
cat /home/yulivee/.cache/wal/sequences

# aliases
alias ls="exa --icons"
alias vim="nvim"
alias tms="tmux new -s"
alias tma="tmux attach"

zle-keymap-select () {
    if [[ $KEYMAP == vicmd ]]; then
        # the command mode for vi
        echo -ne "\e[2 q"
    else
        # the insert mode for vi
        echo -ne "\e[5 q"
    fi
}
precmd_functions+=(zle-keymap-select)
zle -N zle-keymap-select

# the only necessary plugin
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
